// <auto-generated />
using System;
using Data.Layer.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevHub.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909173827_IsViewedColumnToReportAnswersTable")]
    partial class IsViewedColumnToReportAnswersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevHub.Domain.Models.BookmarkedPost", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("BookmarkedPosts");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Software Development"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Programming Languages"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mobile Development"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Infrastructure"
                        },
                        new
                        {
                            Id = 10,
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Automation"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Open Source"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Data Privacy"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Tech Ethics"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Analytics"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Blockchain"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Cryptocurrencies"
                        },
                        new
                        {
                            Id = 20,
                            Name = "AR/VR"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Quantum Computing"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Edge Computing"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Gadgets"
                        },
                        new
                        {
                            Id = 25,
                            Name = "IoT"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Wearables"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Smart Home"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Tech Industry News"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Tech Reviews"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Tech Conferences"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Tech Startups"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Entrepreneurship"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Tech Policy"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Future of Work"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Green Tech"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Sustainability"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Tech Careers"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Productivity Tools"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Workflows"
                        });
                });

            modelBuilder.Entity("DevHub.Domain.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WrittenAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId")
                        .IsUnique()
                        .HasFilter("[ParentCommentId] IS NOT NULL");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DevHub.Domain.Models.CourseChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseChapters");
                });

            modelBuilder.Entity("DevHub.Domain.Models.CourseVideo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseChapterId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseChapterId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseVideos");
                });

            modelBuilder.Entity("DevHub.Domain.Models.ExternalLogin", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginKey");

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("DevHub.Domain.Models.MinimalPost", b =>
                {
                    b.Property<string>("AuthorImageProfileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Author Name");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Category Name");

                    b.Property<string>("FeatureImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinalCount")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("DevHub.Domain.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionName = "CREATE_POST"
                        },
                        new
                        {
                            Id = 2,
                            PermissionName = "DELETE_POST_"
                        },
                        new
                        {
                            Id = 3,
                            PermissionName = "EDIT_POST"
                        },
                        new
                        {
                            Id = 4,
                            PermissionName = "VIEW_POST"
                        });
                });

            modelBuilder.Entity("DevHub.Domain.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("DevHub.Domain.Models.PostImage", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PostId", "ImageUrl");

                    b.ToTable("PostImage");
                });

            modelBuilder.Entity("DevHub.Domain.Models.PostTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("DevHub.Domain.Models.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokeOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("DevHub.Domain.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAdminViewed")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("ReportDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DevHub.Domain.Models.ReportAnswer", b =>
                {
                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("bit");

                    b.Property<string>("ReportDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("ReporterId");

                    b.ToTable("ReportAnswer");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Reader"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Author"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("DevHub.Domain.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AI Tools"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Neural Networks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Deep Learning"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Generative AI"
                        },
                        new
                        {
                            Id = 5,
                            Name = "LLMs"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Prompt Engineering"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Quantum Computing"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Edge Computing"
                        },
                        new
                        {
                            Id = 9,
                            Name = "5G Technology"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Metaverse"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Virtual Reality"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Augmented Reality"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Mixed Reality"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 15,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 16,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 18,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 19,
                            Name = "C++"
                        },
                        new
                        {
                            Id = 20,
                            Name = "C"
                        },
                        new
                        {
                            Id = 21,
                            Name = "GoLang"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Rust"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 24,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Swift"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Objective-C"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Perl"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Scala"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Haskell"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Elixir"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Erlang"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Dart"
                        },
                        new
                        {
                            Id = 34,
                            Name = "R"
                        },
                        new
                        {
                            Id = 35,
                            Name = "MATLAB"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Julia"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Shell Scripting"
                        },
                        new
                        {
                            Id = 38,
                            Name = "PowerShell"
                        },
                        new
                        {
                            Id = 39,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 40,
                            Name = "NoSQL"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Fortran"
                        },
                        new
                        {
                            Id = 42,
                            Name = "COBOL"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Assembly"
                        },
                        new
                        {
                            Id = 44,
                            Name = "F#"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Visual Basic"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Groovy"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Lua"
                        },
                        new
                        {
                            Id = 48,
                            Name = "React"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Vue.js"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Svelte"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Next.js"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Nuxt.js"
                        },
                        new
                        {
                            Id = 55,
                            Name = "iOS Development"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Android Development"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 58,
                            Name = "React Native"
                        },
                        new
                        {
                            Id = 59,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Google Cloud"
                        },
                        new
                        {
                            Id = 62,
                            Name = "SaaS"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Microservices"
                        },
                        new
                        {
                            Id = 64,
                            Name = "API Development"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Containerization"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 67,
                            Name = "CI/CD Pipelines"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Serverless Computing"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Cloud-Native Apps"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Cybersecurity Tips"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Ethical Hacking"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Penetration Testing"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Zero Trust Security"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Cybersecurity Frameworks"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Data Privacy"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Tech Ethics"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Big Data"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Data Visualization"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Machine Learning Models"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Blockchain Basics"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Smart Contracts"
                        },
                        new
                        {
                            Id = 83,
                            Name = "NFTs"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Productivity Hacks"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Remote Work Tools"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Coding Bootcamps"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Tech Career Advice"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Tech Recruiting"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Digital Transformation"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Future of Work"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Gadgets Review"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Wearable Tech"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Smart Home Devices"
                        },
                        new
                        {
                            Id = 94,
                            Name = "IoT Devices"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Open Source"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Tech Startups"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Tech Conferences"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Tech Innovations"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Green Tech"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Sustainable Computing"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Tech Policy"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Tech Trends"
                        });
                });

            modelBuilder.Entity("DevHub.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DevHub.Domain.Models.UserFollower", b =>
                {
                    b.Property<int>("FollowedUserId")
                        .HasColumnType("int");

                    b.Property<int>("FollowerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSince")
                        .HasColumnType("datetime2");

                    b.HasKey("FollowedUserId", "FollowerUserId");

                    b.HasIndex("FollowerUserId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("DevHub.Domain.Models.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermission");
                });

            modelBuilder.Entity("DevHub.Domain.Models.BookmarkedPost", b =>
                {
                    b.HasOne("DevHub.Domain.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHub.Domain.Models.User", "User")
                        .WithMany("BookmarkedPosts")
                        .HasForeignKey("UserId");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Comment", b =>
                {
                    b.HasOne("DevHub.Domain.Models.Comment", null)
                        .WithOne()
                        .HasForeignKey("DevHub.Domain.Models.Comment", "ParentCommentId");

                    b.HasOne("DevHub.Domain.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHub.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Course", b =>
                {
                    b.HasOne("DevHub.Domain.Models.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("DevHub.Domain.Models.CourseChapter", b =>
                {
                    b.HasOne("DevHub.Domain.Models.Course", "Course")
                        .WithMany("CourseChapters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DevHub.Domain.Models.CourseVideo", b =>
                {
                    b.HasOne("DevHub.Domain.Models.CourseChapter", "Chapter")
                        .WithMany("CourseVideos")
                        .HasForeignKey("CourseChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHub.Domain.Models.Course", "Course")
                        .WithMany("CourseVideos")
                        .HasForeignKey("CourseId");

                    b.Navigation("Chapter");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DevHub.Domain.Models.ExternalLogin", b =>
                {
                    b.HasOne("DevHub.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Post", b =>
                {
                    b.HasOne("DevHub.Domain.Models.User", "Author")
                        .WithMany("MyPosts")
                        .HasForeignKey("AuthorId");

                    b.HasOne("DevHub.Domain.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DevHub.Domain.Models.PostImage", b =>
                {
                    b.HasOne("DevHub.Domain.Models.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DevHub.Domain.Models.PostTag", b =>
                {
                    b.HasOne("DevHub.Domain.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHub.Domain.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevHub.Domain.Models.Reaction", b =>
                {
                    b.HasOne("DevHub.Domain.Models.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHub.Domain.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("DevHub.Domain.Models.Reaction", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevHub.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("DevHub.Domain.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Report", b =>
                {
                    b.HasOne("DevHub.Domain.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("DevHub.Domain.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHub.Domain.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevHub.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("Reporter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevHub.Domain.Models.ReportAnswer", b =>
                {
                    b.HasOne("DevHub.Domain.Models.Report", "Report")
                        .WithOne("ReportAnswer")
                        .HasForeignKey("DevHub.Domain.Models.ReportAnswer", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHub.Domain.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("DevHub.Domain.Models.User", b =>
                {
                    b.HasOne("DevHub.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DevHub.Domain.Models.UserFollower", b =>
                {
                    b.HasOne("DevHub.Domain.Models.User", "FollowedUser")
                        .WithMany()
                        .HasForeignKey("FollowedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHub.Domain.Models.User", "FollowerUser")
                        .WithMany()
                        .HasForeignKey("FollowerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowedUser");

                    b.Navigation("FollowerUser");
                });

            modelBuilder.Entity("DevHub.Domain.Models.UserPermission", b =>
                {
                    b.HasOne("DevHub.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHub.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevHub.Domain.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Course", b =>
                {
                    b.Navigation("CourseChapters");

                    b.Navigation("CourseVideos");
                });

            modelBuilder.Entity("DevHub.Domain.Models.CourseChapter", b =>
                {
                    b.Navigation("CourseVideos");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostImages");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("DevHub.Domain.Models.Report", b =>
                {
                    b.Navigation("ReportAnswer")
                        .IsRequired();
                });

            modelBuilder.Entity("DevHub.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DevHub.Domain.Models.User", b =>
                {
                    b.Navigation("BookmarkedPosts");

                    b.Navigation("MyPosts");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
